DataDir: ../data
LogLevel: debug
User: mox
Hostname: mail.example.com

AdminPasswordFile: adminpasswd

Postmaster:
	Account: admin
	Mailbox: Postmaster

Listeners:
	internal:
		IPs:
			- 0.0.0.0

		Hostname: localhost

		AccountHTTP:
			Enabled: true

		AdminHTTP:
			Enabled: true

		WebmailHTTP:
			Enabled: true

		IMAP:
			Enabled: true
