name: Monthly changelog

permissions: {}

on:
  workflow_dispatch:
  schedule:
    # Run at an odd time to avoid spikes at, e.g. midnight.
    # We don't really care too much about the particular time.
    # https://crontab.guru/#17_1_1_*_*
    - cron: "17 1 1 * *"

jobs:
  create-changelog:
    if: github.repository_owner == 'ngi-nix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
          ref: "master"

      - name: Update changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        id: git-cliff
        with:
          version: latest
          config: cliff.toml
          args: --verbose
          github_token: ${{ secrets.FLAKE_UPDATE }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: "update_changelog"
          delete-branch: true
          title: "chore: Update CHANGELOG.md"
          commit-message: "chore: Update CHANGELOG.md"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          token: ${{ secrets.FLAKE_UPDATE }}
          labels: automated
          body: |
            Update changelog.

            *PR auto-generated by the [monthly changelog workflow](../actions/workflows/monthly-changelog.yml).*
